import type { GetServerSideProps } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import CheckBox from "../components/CheckBox";

interface Props {
  prefectures: Element[];
}

interface Element {
  prefCode: number;
  prefName: string;
}

const Home: React.VFC<Props> = ({ prefectures }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>utsuroi app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1>utsuroi app</h1>
        <div>
          {prefectures.map((prefecture) => (
            <div key={prefecture.prefCode}>
              <CheckBox prefName={prefecture.prefName} />
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const url = "https://opendata.resas-portal.go.jp/api/v1/prefectures";
  const apiKey = process.env.X_API_KEY || "";

  const res = await fetch(url, { headers: { "X-API-KEY": apiKey } });
  const prefecturesJson = await res.json();
  const prefectures = prefecturesJson.result;

  return {
    props: { prefectures },
  };
};

export default Home;
